# Generated by Django 4.1.2 on 2022-10-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostup2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('employee', 'date_created'), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders', verbose_name='file'),
        ),
    ]
